### ISSUE TITLE
No matching distribution found for MultiScaleDeformableAttention==1.0

### ISSUE THREAD

**Issue by BrunoMelicio** [shreyashampali/kypt_transformer#1]
Hello,
I am trying to install the requirements but I get an error on MultiScaleDeformableAttention==1.0. I have also tried without the ==1.0 but the error persists. 
Could you please tell me how to solve it?
Thank you in advance.

**Comment by arkincognito** [comment]
Same problem. I even tried installing with the .whl file from the [pypi page](https://pypi.org/project/MultiScaleDeformableAttention/) but pip throws `ERROR: MultiScaleDeformableAttention-0.1-none-any.whl is not a valid wheel filename.`

**Comment by shreyashampali** [comment]
Hi,
Sorry for the delay. MultiScaleDeformableAttention is not required for this project. I have updated the requirements.txt. Can you please try with the new file?
