### ISSUE TITLE
Demo error

### ISSUE THREAD

**Issue by redorangeyellowy** [shreyashampali/kypt_transformer#2]
Thank you for your excellent research.

As a result of implementing `demo.py` using the checkpoint you provided (`snapshot_4_2000.pth.tar`), the following error occurred. 

```
RuntimeError: Error(s) in loading state_dict for DataParallel:
	size mismatch for module.query_embed.weight: copying a param with shape torch.Size([34, 256]) from checkpoint, the shape in current model is torch.Size([43, 256]).
```

I think the problem is caused by the size difference between the loaded model and the current model,

so I wonder how to solve it.

**Comment by shreyashampali** [comment]
hi @redorangeyellowy 
thanks for your interest. 
Have you set  `dataset = 'InterHand2.6M'` and `pose_representation = 'angles'` in config.py ?

**Comment by redorangeyellowy** [comment]
Thanks. 

I think there is an error like that because it was set to `2p5D` at first.

However, the following error occurs when I set it to `angle`.

```
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
```

Does this code work only on the device with the display?

**Comment by shreyashampali** [comment]
Yes, its the demo code and an open3d window is shown. I don't think it works without a display.

**Comment by redorangeyellowy** [comment]
Okay. Thank you for your reply.
