### ISSUE TITLE
Can not find file InterHand2.6M_test_MANO.json

### ISSUE THREAD

**Issue by XIANGLINYUN** [shreyashampali/kypt_transformer#3]
Hello,
I am trying to run the demo.py with InterHand2.6M dataset, but I can't find the necessary json file named  InterHand2.6M_test_MANO.json from the homepage of InterHand2.6M. Could you please tell me where can I find it?

Thank you

**Comment by redorangeyellowy** [comment]
So I just used `InterHand2.6M_test_MANO_NeuralAnnot.json` in this [link](https://drive.google.com/drive/folders/1neLObZ65WcW7tVYufPs7I7-jT0lpEoDX).

Is there any problem...?

**Comment by shreyashampali** [comment]
Yes you can use InterHand2.6M_test_MANO_NeuralAnnot.json

**Comment by XIANGLINYUN** [comment]
> Yes you can use InterHand2.6M_test_MANO_NeuralAnnot.json

Thank you for reply
