### ISSUE TITLE
Shouldn't PoseLoss normalizer value initialize to 0 instead of 32?

### ISSUE THREAD

**Issue by arkincognito** [shreyashampali/kypt_transformer#5]
Hi,
in `loss.py` `PoseLoss.forward()`, `normalizer` is initialized to 32.
I see the logic is that for each hand, there are 16 joints, so you wanted to add 16 to the `normalizer` per hand.
However, since you initialized `normalizer = 32`, if you have "left" in `cfg.hand_type`, you'll end up with 48 for normalizer.

**Comment by shreyashampali** [comment]
Hi,
hand_type is always set to `both` as mentioned in `config.py`.
Other configurations will not work. When there is a single hand (like HO-3D dataset), the queries belonging to the other hand are ignored.

**Comment by arkincognito** [comment]
Thanks for the response. I thought the hand_type settings in config.py were interchangeable.
